const countryCode = {
  AF: "Afghanistan",
  AL: "Albania",
  DZ: "Algeria",
  AS: "American Samoa",
  // AD: "Andorra",
  // AO: "Angola",
  // AI: "Anguilla",
  // AQ: "Antarctica",
  // AG: "Antigua and Barbuda",
  // AR: "Argentina",
  // AM: "Armenia",
  // AW: "Aruba",
  // AU: "Australia",
  // AT: "Austria",
  // AZ: "Azerbaijan",
  // BS: "Bahamas (the)",
  // BH: "Bahrain",
  // BD: "Bangladesh",
  // BB: "Barbados",
  // BY: "Belarus",
  // BE: "Belgium",
  // BZ: "Belize",
  // BJ: "Benin",
  // BM: "Bermuda",
  // BT: "Bhutan",
  // BO: "Bolivia (Plurinational State of)",
  // BQ: "Bonaire, Sint Eustatius and Saba",
  // BA: "Bosnia and Herzegovina",
  // BW: "Botswana",
  // BV: "Bouvet Island",
  // BR: "Brazil",
  // IO: "British Indian Ocean Territory (the)",
  // BN: "Brunei Darussalam",
  // BG: "Bulgaria",
  // BF: "Burkina Faso",
  // BI: "Burundi",
  // CV: "Cabo Verde",
  // KH: "Cambodia",
  // CM: "Cameroon",
  // CA: "Canada",
  // KY: "Cayman Islands (the)",
  // CF: "Central African Republic (the)",
  // TD: "Chad",
  // CL: "Chile",
  // CN: "China",
  // CX: "Christmas Island",
  // CC: "Cocos (Keeling) Islands (the)",
  // CO: "Colombia",
  // KM: "Comoros (the)",
  // CD: "Congo (the Democratic Republic of the)",
  // CG: "Congo (the)",
  // CK: "Cook Islands (the)",
  // CR: "Costa Rica",
  // HR: "Croatia",
  // CU: "Cuba",
  // CW: "Curaçao",
  // CY: "Cyprus",
  // CZ: "Czechia",
  // CI: "Côte d'Ivoire",
  // DK: "Denmark",
  // DJ: "Djibouti",
  // DM: "Dominica",
  // DO: "Dominican Republic (the)",
  // EC: "Ecuador",
  // EG: "Egypt",
  // SV: "El Salvador",
  // GQ: "Equatorial Guinea",
  // ER: "Eritrea",
  // EE: "Estonia",
  // SZ: "Eswatini",
  // ET: "Ethiopia",
  // FK: "Falkland Islands (the) [Malvinas]",
  // FO: "Faroe Islands (the)",
  // FJ: "Fiji",
  // FI: "Finland",
  // FR: "France",
  // GF: "French Guiana",
  // PF: "French Polynesia",
  // TF: "French Southern Territories (the)",
  // GA: "Gabon",
  // GM: "Gambia (the)",
  // GE: "Georgia",
  // DE: "Germany",
  // GH: "Ghana",
  // GI: "Gibraltar",
  // GR: "Greece",
  // GL: "Greenland",
  // GD: "Grenada",
  // GP: "Guadeloupe",
  // GU: "Guam",
  // GT: "Guatemala",
  // GG: "Guernsey",
  // GN: "Guinea",
  // GW: "Guinea-Bissau",
  // GY: "Guyana",
  // HT: "Haiti",
  // HM: "Heard Island and McDonald Islands",
  // VA: "Holy See (the)",
  // HN: "Honduras",
  // HK: "Hong Kong",
  // HU: "Hungary",
  // IS: "Iceland",
  // IN: "India",
  // ID: "Indonesia",
  // IR: "Iran (Islamic Republic of)",
  // IQ: "Iraq",
  // IE: "Ireland",
  // IM: "Isle of Man",
  // IL: "Israel",
  // IT: "Italy",
  // JM: "Jamaica",
  // JP: "Japan",
  // JE: "Jersey",
  // JO: "Jordan",
  // KZ: "Kazakhstan",
  // KE: "Kenya",
  // KI: "Kiribati",
  // KP: "Korea (the Democratic People's Republic of)",
  // KR: "Korea (the Republic of)",
  // KW: "Kuwait",
  // KG: "Kyrgyzstan",
  // LA: "Lao People's Democratic Republic (the)",
  // LV: "Latvia",
  // LB: "Lebanon",
  // LS: "Lesotho",
  // LR: "Liberia",
  // LY: "Libya",
  // LI: "Liechtenstein",
  // LT: "Lithuania",
  // LU: "Luxembourg",
  // MO: "Macao",
  // MG: "Madagascar",
  // MW: "Malawi",
  // MY: "Malaysia",
  // MV: "Maldives",
  // ML: "Mali",
  // MT: "Malta",
  // MH: "Marshall Islands (the)",
  // MQ: "Martinique",
  // MR: "Mauritania",
  // MU: "Mauritius",
  // YT: "Mayotte",
  // MX: "Mexico",
  // FM: "Micronesia (Federated States of)",
  // MD: "Moldova (the Republic of)",
  // MC: "Monaco",
  // MN: "Mongolia",
  // ME: "Montenegro",
  // MS: "Montserrat",
  // MA: "Morocco",
  // MZ: "Mozambique",
  // MM: "Myanmar",
  // NA: "Namibia",
  // NR: "Nauru",
  // NP: "Nepal",
  // NL: "Netherlands (the)",
  // NC: "New Caledonia",
  // NZ: "New Zealand",
  // NI: "Nicaragua",
  // NE: "Niger (the)",
  // NG: "Nigeria",
  // NU: "Niue",
  // NF: "Norfolk Island",
  // MP: "Northern Mariana Islands (the)",
  // NO: "Norway",
  // OM: "Oman",
  // PK: "Pakistan",
  // PW: "Palau",
  // PS: "Palestine, State of",
  // PA: "Panama",
  // PG: "Papua New Guinea",
  // PY: "Paraguay",
  // PE: "Peru",
  // PH: "Philippines (the)",
  // PN: "Pitcairn",
  // PL: "Poland",
  // PT: "Portugal",
  // PR: "Puerto Rico",
  // QA: "Qatar",
  // MK: "Republic of North Macedonia",
  // RO: "Romania",
  // RU: "Russian Federation (the)",
  // RW: "Rwanda",
  // RE: "Réunion",
  // BL: "Saint Barthélemy",
  // SH: "Saint Helena, Ascension and Tristan da Cunha",
  // KN: "Saint Kitts and Nevis",
  // LC: "Saint Lucia",
  // MF: "Saint Martin (French part)",
  // PM: "Saint Pierre and Miquelon",
  // VC: "Saint Vincent and the Grenadines",
  // WS: "Samoa",
  // SM: "San Marino",
  // ST: "Sao Tome and Principe",
  // SA: "Saudi Arabia",
  // SN: "Senegal",
  // RS: "Serbia",
  // SC: "Seychelles",
  // SL: "Sierra Leone",
  // SG: "Singapore",
  // SX: "Sint Maarten (Dutch part)",
  // SK: "Slovakia",
  // SI: "Slovenia",
  // SB: "Solomon Islands",
  // SO: "Somalia",
  // ZA: "South Africa",
  // GS: "South Georgia and the South Sandwich Islands",
  // SS: "South Sudan",
  // ES: "Spain",
  // LK: "Sri Lanka",
  // SD: "Sudan (the)",
  // SR: "Suriname",
  // SJ: "Svalbard and Jan Mayen",
  // SE: "Sweden",
  // CH: "Switzerland",
  // SY: "Syrian Arab Republic",
  // TW: "Taiwan (Province of China)",
  // TJ: "Tajikistan",
  // TZ: "Tanzania, United Republic of",
  // TH: "Thailand",
  // TL: "Timor-Leste",
  // TG: "Togo",
  // TK: "Tokelau",
  // TO: "Tonga",
  // TT: "Trinidad and Tobago",
  // TN: "Tunisia",
  // TR: "Turkey",
  // TM: "Turkmenistan",
  // TC: "Turks and Caicos Islands (the)",
  // TV: "Tuvalu",
  // UG: "Uganda",
  // UA: "Ukraine",
  // AE: "United Arab Emirates (the)",
  // GB: "United Kingdom of Great Britain and Northern Ireland (the)",
  // UM: "United States Minor Outlying Islands (the)",
  // US: "United States of America (the)",
  // UY: "Uruguay",
  // UZ: "Uzbekistan",
  // VU: "Vanuatu",
  // VE: "Venezuela (Bolivarian Republic of)",
  // VN: "Viet Nam",
  // VG: "Virgin Islands (British)",
  // VI: "Virgin Islands (U.S.)",
  // WF: "Wallis and Futuna",
  // EH: "Western Sahara",
  // YE: "Yemen",
  // ZM: "Zambia",
  // ZW: "Zimbabwe",
  // AX: "Åland Islands",
};

const countryList = {
  AF: 1,
  AL: 2,
  DZ: 3,
  AS: 4,
  // AD: 5,
  // AO: 6,
  // AI: 7,
  // AQ: 8,
  // AG: 9,
  // AR: 10,
  // AM: 11,
  // AW: 12,
  // AU: 13,
  // AT: 14,
  // AZ: 15,
  // BS: 16,
  // BH: 17,
  // BD: 18,
  // BB: 19,
  // BY: 20,
  // BE: 21,
  // BZ: 22,
  // BJ: 23,
  // BM: 24,
  // BT: 25,
  // BO: 26,
  // BQ: 27,
  // BA: 28,
  // BW: 29,
  // BV: 30,
  // BR: 31,
  // IO: 32,
  // BN: 33,
  // BG: 34,
  // BF: 35,
  // BI: 36,
  // CV: 37,
  // KH: 38,
  // CM: 39,
  // CA: 40,
  // KY: 41,
  // CF: 42,
  // TD: 43,
  // CL: 44,
  // CN: 45,
  // CX: 46,
  // CC: 47,
  // CO: 48,
  // KM: 49,
  // CD: 50,
  // CG: 51,
  // CK: 52,
  // CR: 53,
  // HR: 54,
  // CU: 55,
  // CW: 56,
  // CY: 57,
  // CZ: 58,
  // CI: 59,
  // DK: 60,
  // DJ: 61,
  // DM: 62,
  // DO: 63,
  // EC: 64,
  // EG: 65,
  // SV: 66,
  // GQ: 67,
  // ER: 68,
  // EE: 69,
  // SZ: 70,
  // ET: 71,
  // FK: 72,
  // FO: 73,
  // FJ: 74,
  // FI: 75,
  // FR: 76,
  // GF: 77,
  // PF: 78,
  // TF: 79,
  // GA: 80,
  // GM: 81,
  // GE: 82,
  // DE: 83,
  // GH: 84,
  // GI: 85,
  // GR: 86,
  // GL: 87,
  // GD: 88,
  // GP: 89,
  // GU: 90,
  // GT: 91,
  // GG: 92,
  // GN: 93,
  // GW: 94,
  // GY: 95,
  // HT: 96,
  // HM: 97,
  // VA: 98,
  // HN: 99,
  // HK: 100,
  // HU: 101,
  // IS: 102,
  // IN: 103,
  // ID: 104,
  // IR: 105,
  // IQ: 106,
  // IE: 107,
  // IM: 108,
  // IL: 109,
  // IT: 110,
  // JM: 111,
  // JP: 112,
  // JE: 113,
  // JO: 114,
  // KZ: 115,
  // KE: 116,
  // KI: 117,
  // KP: 118,
  // KR: 119,
  // KW: 120,
  // KG: 121,
  // LA: 122,
  // LV: 123,
  // LB: 124,
  // LS: 125,
  // LR: 126,
  // LY: 127,
  // LI: 128,
  // LT: 129,
  // LU: 130,
  // MO: 131,
  // MG: 132,
  // MW: 133,
  // MY: 134,
  // MV: 135,
  // ML: 136,
  // MT: 137,
  // MH: 138,
  // MQ: 139,
  // MR: 140,
  // MU: 141,
  // YT: 142,
  // MX: 143,
  // FM: 144,
  // MD: 145,
  // MC: 146,
  // MN: 147,
  // ME: 148,
  // MS: 149,
  // MA: 150,
  // MZ: 151,
  // MM: 152,
  // NA: 153,
  // NR: 154,
  // NP: 155,
  // NL: 156,
  // NC: 157,
  // NZ: 158,
  // NI: 159,
  // NE: 160,
  // NG: 161,
  // NU: 162,
  // NF: 163,
  // MP: 164,
  // NO: 165,
  // OM: 166,
  // PK: 167,
  // PW: 168,
  // PS: 169,
  // PA: 170,
  // PG: 171,
  // PY: 172,
  // PE: 173,
  // PH: 174,
  // PN: 175,
  // PL: 176,
  // PT: 177,
  // PR: 178,
  // QA: 179,
  // MK: 180,
  // RO: 181,
  // RU: 182,
  // RW: 183,
  // RE: 184,
  // BL: 185,
  // SH: 186,
  // KN: 187,
  // LC: 188,
  // MF: 189,
  // PM: 190,
  // VC: 191,
  // WS: 192,
  // SM: 193,
  // ST: 194,
  // SA: 195,
  // SN: 196,
  // RS: 197,
  // SC: 198,
  // SL: 199,
  // SG: 200,
  // SX: 201,
  // SK: 202,
  // SI: 203,
  // SB: 204,
  // SO: 205,
  // ZA: 206,
  // GS: 207,
  // SS: 208,
  // ES: 209,
  // LK: 210,
  // SD: 211,
  // SR: 212,
  // SJ: 213,
  // SE: 214,
  // CH: 215,
  // SY: 216,
  // TW: 217,
  // TJ: 218,
  // TZ: 219,
  // TH: 220,
  // TL: 221,
  // TG: 222,
  // TK: 223,
  // TO: 224,
  // TT: 225,
  // TN: 226,
  // TR: 227,
  // TM: 228,
  // TC: 229,
  // TV: 230,
  // UG: 231,
  // UA: 232,
  // AE: 233,
  // GB: 234,
  // UM: 235,
  // US: 236,
  // UY: 237,
  // UZ: 238,
  // VU: 239,
  // VE: 240,
  // VN: 241,
  // VG: 242,
  // VI: 243,
  // WF: 244,
  // EH: 245,
  // YE: 246,
  // ZM: 247,
  // ZW: 248,
  // AX: 249,
};

const Constants = {
  countryList,
  countryCode,
};

module.exports = Constants;
